### ISSUE TITLE
Build-Prozess mit GitHub Actions automatisieren

### ISSUE THREAD

**Issue by McPringle** [ijug-ev/monika#1]
Im Repo befindet sich eine Konfiguration für GitLab, die als Vorlage dienen kann.

**Comment by mkarg** [comment]
Erledigt mittels https://github.com/ijug-ev/monika/blob/master/.github/workflows/build-and-deploy.yml.

Github Actions erzeugt bei jedem `git push` in den 👱🏻‍♀️ Monika's `master`-branche ein neues Containerimage und legt es unter `ghcr.io/ijug-ev/monika:latest` ab. Zur Beschleunigung des Buildvorgangs wird dabei ein Github Cache verwendet, in dem das lokale Maven-Repository gespeichert wird, womit alle Dependencies "am Stück" in den Build-Container kommen. 🏎️ 

Der erzeugte Container ist bereits auf 🦣 ijug.social im Einsatz. 😄
